### ISSUE TITLE
Don't unconditionally return `nullptr` from wise_enum_detail_to_string

### ISSUE THREAD

**Issue by JonasProgrammer** [quicknir/wise_enum#13]
Currently `wise_enum_detail_to_string` unconditionally returns `nullptr`, if the enum value passed to `to_string` is not found (which is easy quite easy to do, for example default-constructing an `enum class` not starting at 0 or using a partially-adapted 3rd party enum).

This causes a problem, however, with C++17, as the library defaults to using `std::string_view`. While GCC 8.2 seems to work fine, both GCC 9 trunk and Clang 7 segfault on execution.

The problem is likely the following: As per 24.2.1 `[string.view.cons]`, constructing from a `nullptr` uses the implicit one-argument constructor taking `charT const*`, which in turn relies on `traits::length` to get the size of the passed string.

24.2.1 `[char.traits.require]` now states, that `length(p)` *Returns*: the smallest `i` such that `X::eq(p[i],charT())` is `true`. So even for `i == 0`, `eq(p[i], charT())` must be checked (although GCC 8.2's implementation seems to bail out here), which results in `nullptr` being dereferenced.

So far, I see two ways of getting about this: either return a default-constructed `string_type` (which is a 0-length `nullptr`d for `string_view` and `nullptr` for `char const*` or introduce a `constexpr string_type invalid_enum_value_string` variable, which defaults to a default-constructed `string_type` and is customizable via a macro.

**Comment by JonasProgrammer** [comment]
#14 attempts to fix the issue in the latter way described.

**Comment by quicknir** [comment]
Good catch! I'm not quite sure about the approach; the issue with customization macros is that if e.g. a mid sized company wants to use the library, it's 100% essential that everywhere the macros are defined the same ways, even in two pieces of software that are very loosely coupled, if they are part of the same process (or else risk ODR violation madness). I've used them exclusively for things that somewhat inevitably vary from version to version of C++, which generally also has to match across a company codebase. Here though you could imagine two different libraries written by two different teams at the same company deciding to define this differently from convenience.

I think a better approach might be to simply hardcode the empty string, as its a low cost sentinel that cannot be mistaken for a true value. If users want to output something more intelligent than an empty string for e.g. a log, I think it's reasonable to have them branch on an empty string and insert whatever they prefer.

Thoughts?

**Comment by quicknir** [comment]
To add to that, the "right" string for the enum not being found, in many people's estimation would be a per-enum decision anyhow, so a customization point fraught with hazards that lets you customize it globally seems not worthwhile.

Anyhow perhaps I'm missing something else in this discussion, so I'm open to my mind being changed.

**Comment by JonasProgrammer** [comment]
I wasn't quite sure about the right approach either, my original fix was indeed simply returning `{}`. Seeing all the customization macros I simply thought this was the preferred way and I wanted to offer a 'proper' PR, if I already make people read standardeese gibberish.

I thoroughly agree with your points, why doing it in the way it is currently done is a bad way. I'd refrain, however, form returning an empty string (at least, if you were referring to returning `""`).
I think the default-construction approach is better here. Not only does it keep the current behaviour for `char const*`, in case anybody relies on that, it also gives sensible results for `string_view` and `string`. The only drawback I can think of, would be that `string_type` has to be default-constructable; I cannot think of a case, however, where someone would use such a type.

The coolest option IMHO is a specializable template with the *not-found* value being a `constexpr` depending on the enum type (defaulting to `{}` in a non-specialized scenario), but then again that's a lot of work for just saving the callee an if statement.

**Comment by quicknir** [comment]
Cool, thanks for your response. I'm not too concerned at this point with the backwards compatibility break; the user base is relatively small for now and I've been careful about semantic versioning things correctly (and there's a break coming up where I reduce the default number of maximum enumerators to suit MSVC). I guess it boils down to null pointer for const char* vs "". I think you are right though that for const char* null pointer does seem more idiomatic.

I'll push a fix for this on the weekend and then close this. Thanks again for catching this; really highlights the need for proper CI, but I just haven't had time to set it up.

**Comment by JonasProgrammer** [comment]
Just in case it helps, I do have two unit tests lying around here, which I wrote to test whether my implementation works. They're horribly ugly and rely on conan and cmake, but they could be a starting point.

If you want, I can also try and get this stuff set up with travis.

**Comment by quicknir** [comment]
@JonasProgrammer If you want to help with travis, that would be big! I can open a separate issue for that (or you can). Re dependencies for unit test, I'm definitely fine with cmake, conan is also fine as long as it can easily be changed if necessary. I would like to use boost unit if possible, as I'm trying to get this into boost (it will remain available as a standalone library as well and will not depend on anything else in boost), not sure what framework you used.
