### ISSUE TITLE
Does not compile under C++ 11

### ISSUE THREAD

**Issue by ilazaric** [quicknir/wise_enum#18]
`g++ -std=c++11 example.x.cpp` does not compile.
The version of `g++` is `5.4.0`.
One of the problems is using `std::underlying_type_t<T>`, should be `std::underlying_type<T>::type`.

**Comment by quicknir** [comment]
Thanks for this, I will check it out. We're in the process of adding CI which will hopefully catch these issues.

**Comment by quicknir** [comment]
It seems like the only place underlying_type_t is currently used, is in example (which isn't c++11 compatible; use example11), and in compact_optional, which requires c++14 (I need to be able to do for loops, constexpr). So at present, it seems like this is handled. Please open another issue if you see compilation issues with C++11 again!
