### ISSUE TITLE
Converting to / from index

### ISSUE THREAD

**Issue by NikolausDemmel** [quicknir/wise_enum#30]
There is `range` and `size`. Is there also a direct way to get the n'th enum value, and vice-versa, the index in the range for a given enum value?

I guess both could be done easily by iterating over the range, but I was woundering if there is direct way.

**Comment by quicknir** [comment]
Well, range is a contiguous range. In particular it's just a std::array. So you are more than welcome to access it directly with []. I think it's safe to say that I consider this part of the API and don't plan to change it.

To go from a given enum value to index, you can do by calling `find`, which would do linear search. I could maybe implement this ability as switch case but I don't know if I see a good use case. Do you have one?

**Comment by NikolausDemmel** [comment]
> Well, range is a contiguous range. In particular it's just a std::array. So you are more than welcome to access it directly with []. 

Ah, that makes it easy, thanks.

> To go from a given enum value to index, you can do by calling find, which would do linear search.

Ah ok, that would work with iterator arithmetic, thanks.

> I could maybe implement this ability as switch case but I don't know if I see a good use case. Do you have one?

The use case is some automatic GUI elements to change an enum value. I do it with a slider for the index and text field showing the currently selected value's string representation.

With your suggestions I think its already sufficiently simple to be honest.

**Comment by quicknir** [comment]
Sounds good!

**Comment by NikolausDemmel** [comment]
Just for future reference, I now have something like:

```
  int get_index() const override {
    auto begin = std::begin(wise_enum::range<EnumType>);
    auto end = std::end(wise_enum::range<EnumType>);
    auto it =
        std::find_if(begin, end, [&](auto& e) { return e.value == value_; });
    if (it == end) {
      LOG(FATAL) << "Unreachable";
    }
    return it - begin;
  }

  bool set_index(int index) override {
    if (index < 0 || index >= static_cast<int>(wise_enum::size<EnumType>) {
      return false;
    } else {
      value_ = wise_enum::range<EnumType>[index].value;
      return true;
    }
  }
```

Thanks for this useful library.
