### ISSUE TITLE
Can't override optional

### ISSUE THREAD

**Issue by andre-nguyen** [quicknir/wise_enum#34]
The readme says we can define `WISE_ENUM_OPTIONAL` to override the internal optional implementation, but I don't see this macro used anywhere. Is this supported?

**Comment by andre-nguyen** [comment]
It looks like the readme is wrong and the real macro is `WISE_ENUM_OPTIONAL_TYPE`

**Comment by quicknir** [comment]
@andre-nguyen I'll leave this issue open as a reminder to fix the readme, thank you.
