### ISSUE TITLE
Move examples to subfolder

### ISSUE THREAD

**Issue by ramboerik** [quicknir/wise_enum#36]
Hi,

I'm using this library with build system [platformIO](https://platformio.org/) and stumbled over a minor problem. platformIO supports external git dependencies and manages the download/compile all by itself but the problem is that it compiles all sources in the root of the repo. `example.x.cpp`  and `example11.x.cpp` get compiled and I get an error for multiple definitions of `main()` . Could you move the examples to a separate folder, e. g. `examples/` ? This would make the library perfect compatible with platformIO!

**Comment by quicknir** [comment]
Sure, make a pull request and I'll merge it.
