### ISSUE TITLE
string_type is `string_view` for C++17 and `const char *` for C++20

### ISSUE THREAD

**Issue by davidstone** [quicknir/wise_enum#38]
Rather than checking for an exact match for the C++ version string of `#if __cplusplus == 201703L`, it should at least check with `>=`. Better still would be to check `#ifdef __cpp_lib_string_view`, as that will check exactly what you are trying to test.

**Comment by davidstone** [comment]
Same thing in the same file for `optional`, where the feature test macro is `__cpp_lib_optional`

**Comment by quicknir** [comment]
Thanks for pointing that out! If easier for you, you can submit a PR which I'll merge shortly, otherwise I'll do it soon.

**Comment by davidstone** [comment]
Submitting PR now
