### ISSUE TITLE
New version tag?

### ISSUE THREAD

**Issue by durka** [quicknir/wise_enum#52]
Hi,

I am not sure of the maintenance status of this repo, but there have been at least a few fixes merged since the 3.0.0 tag, which are difficult to use through distributions such as Conan without a tag. Are you planning to make another release?

**Comment by quicknir** [comment]
It's not *unmaintained*, I just haven't done anything active with it in a bit. I am thinking of taking another look at it now; someone suggested making it available in godbolt. I will look into cutting a new release (it's been so long I don't remember how, but I'll figure it out 😛 ).

**Comment by durka** [comment]
Great! Didn't mean to imply any shaming. Also I agree it'd be super useful to have this on godbolt!

**Comment by quicknir** [comment]
Unashamed, no worries! And cutting the release made me realize how much people have contributed to this project, I'm quite shocked!. Thanks for pushing me to release; 3.1.0 is out. If there are any issues please don't hesitate to reopen!
